# Generated by Django 4.0.4 on 2022-05-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Marque', models.CharField(max_length=100)),
                ('pays_Marque', models.CharField(max_length=100)),
                ('date_parution_Marque', models.DateField(blank=True, null=True)),
                ('nombre_modele', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=100)),
                ('pays_modele', models.CharField(max_length=100)),
                ('date_creation_modele', models.DateField(blank=True, null=True)),
                ('nombre_modele', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('marque', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Voiture.marque')),
            ],
        ),
    ]
